name: Auto PR on Feature Push with AI Summary

on:
  push:
    branches:
      - 'feature/**'

jobs:
  auto-create-pr:
    runs-on: ubuntu-latest    
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git fetch origin dev

    - name: Install GitHub CLI
      run: |
        sudo apt install gh -y

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.PR_CREATION_TOKEN}}" | gh auth login --with-token

    - name: Create Pull Request
      run: |
        gh pr create \
          --base dev \
          --head ${{ github.ref_name }} \
          --title "Auto PR: ${{ github.ref_name }}" \
          --body-file summary.md || echo "PR may already exist"
